New source: BiGG Models Metabolite Database
biopragmatics/pyobo pull request #124
Opened 2021-11-10 14:41 UTC by samuelbunga

@cthoyt  This is still a work in progress PR.
- Technically this script should do mappings for BiGG iD and its respective name. For some reason, I am having difficulties in calling the `get_obo` function. Could you please test it on your end and see where I am going wrong?

Thanks!

2021-11-10 14:58 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +    for r, c in bigg_df.iterrows():
iterating directly over `bigg_df.values` is more efficient. Use in combination with `usecols=...` in the `ensure_df()` function to only get the columns you nedd for iteration

2021-11-10 14:59 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +from pyobo.path_utils import ensure_df, ensure_tar_df
replace this with `pyobo.utils.path`

2021-11-10 15:00 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +            definition=[],
invalid type for definition

2021-11-10 15:00 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +            definition=[],
`tox -e mypy` will notify you of stuff like this

2021-11-12 04:01 UTC, samuelbunga commented
Hi Charlie, I just added new changes. Please review them in your free time. Thanks!

2021-11-12 13:12 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +    for v in bigg_df.values:
`v` is a bad variable name. Better is to use tuple unpacking

```suggestion
    for bigg_id, name in bigg_df.values:
```

2021-11-12 13:14 UTC, cthoyt requested changes

2021-11-12 13:14 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +        usecols=['bigg_id', 'name'],
what about the other columns? `database_links` has lots of information worth parsing out, for example. `old_bigg_ids` can be put in the alternative identifier field in the `pyobo.Term`

2021-11-12 13:14 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +def get_terms(force: bool = False, version: Optional[str] = None) -> Iterable[Term]:
check CI - this needs a docstring

2021-11-12 13:17 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +"""Converter for bigg."""
fix stylization of BiGG

2021-11-12 13:18 UTC, cthoyt requested changes

2021-11-12 13:18 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +    """Get bigg as OBO."""
stylization

2021-11-12 13:18 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +    # version = '1.2'
remove dead code

2021-11-12 13:18 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +        name="bigg models metabolites database",
title case + stylization

2021-11-12 13:18 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +        typedefs=[has_role],
why is this included?

2021-11-12 13:18 UTC, cthoyt commented on src/pyobo/sources/bigg.py
> +        synonyms = []
why include this blank list?

2024-12-04 14:44 UTC, merged